apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.namespace }}
        role: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.repository }}
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 60
            periodSeconds: 60
          livenessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 60
            periodSeconds: 60
          envFrom:
            - configMapRef:
                name: services-info
            - configMapRef:
                name: database-common
            - configMapRef:
                name: database-read
          ports:
            - name: {{ .Values.name }}
              containerPort: {{ .Values.port }}
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.namespace }}
    role: {{ .Values.name }}
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
